/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Game */
        post: operations["create_game"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Play Move
         * @description Record a move and return the updated game.
         */
        post: operations["play_move"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BoardStatus
         * @enum {string}
         */
        BoardStatus: "open" | "won" | "drawn";
        /** ErrorResponse */
        ErrorResponse: {
            /**
             * Code
             * @example wrong_board
             */
            code: string;
            /**
             * Detail
             * @example This move must be played in board 4.
             */
            detail: string;
        };
        /** GameRead */
        GameRead: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            status: components["schemas"]["GameStatus"];
            winner: components["schemas"]["Player"] | null;
            current_player: components["schemas"]["Player"] | null;
            /**
             * Active Board
             * @description The board the next move must go in, or null when any open board is allowed.
             */
            active_board: number | null;
            /** Boards */
            boards: components["schemas"]["SmallBoardRead"][];
            /** Moves */
            moves: components["schemas"]["MoveRead"][];
        };
        /**
         * GameStatus
         * @enum {string}
         */
        GameStatus: "in_progress" | "won" | "drawn";
        /** MoveCreate */
        MoveCreate: {
            /**
             * Board
             * @description Small board, 0-8, left to right then top to bottom.
             */
            board: number;
            /**
             * Cell
             * @description Square within that board, 0-8, same ordering.
             */
            cell: number;
        };
        /** MoveRead */
        MoveRead: {
            /** Sequence */
            sequence: number;
            /** Board */
            board: number;
            /** Cell */
            cell: number;
            player: components["schemas"]["Player"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Player
         * @enum {string}
         */
        Player: "x" | "o";
        /** SmallBoardRead */
        SmallBoardRead: {
            /** Index */
            index: number;
            /** Cells */
            cells: (components["schemas"]["Player"] | null)[];
            status: components["schemas"]["BoardStatus"];
            winner: components["schemas"]["Player"] | null;
            /**
             * Playable
             * @description Whether the next move may be played in this board.
             */
            playable: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_game: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRead"];
                };
            };
        };
    };
    get_game: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRead"];
                };
            };
            /** @description The game does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request failed schema validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    play_move: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRead"];
                };
            };
            /** @description The game does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A game rule refused the move. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The request failed schema validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
